# Site settings
title: "人人都可以练习拳击"
logo: logo.png
email: lucas_shao@126.com
description: > # this means to ignore newlines until "baseurl:"
  像蝴蝶一样飞舞,像蜜蜂一样蛰刺
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site  http://127.0.0.1:4000
baseurl: "" # the subpath of your site, e.g. /blog/
timezone: Asia/Shanghai
twitter_username: lucas_shao
github_username:  lucas_shao

# Build settings
markdown: kramdown
